

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - env.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  entrytracker:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - env.env
    networks:
      - backend-network
      - frontend-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - entrytracker
    networks:
      - frontend-network

volumes:
  db_data:

networks:
  backend-network:
  frontend-network:
